name: Run gittuf demo
on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:
jobs:
  run-demo:
    name: Run demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout demo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Install gittuf
        uses: gittuf/gittuf-installer@74bc31fb990a714302c6cf75f91cccdaf33961bc
        with:
          gittuf-version: '0.1.0'
      - name: Install GPG
        run: |
          sudo apt-get update
          sudo apt-get install -y gpg
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -r requirements.txt
      - name: Run demo with --no-prompt
        run: |
          python3 run-demo.py --no-prompt
